name: Test Github Workflow
 
on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: ["on-demand-test"]

jobs:
    hello-world :
      runs-on: ubuntu-latest
      steps:
        - name: Run tests
          run: echo "Hello World"  
    second-job:
      runs-on: windows-latest
      needs: hello-world
      steps:
        - name: Run tests
          run: echo "This job is running on ${{ runner.os }}"


          # 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